CREATE TABLE `aisa_macro_snapshot_monthly` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `snap_month` date DEFAULT NULL COMMENT '数据快照所属月份',
  `cpi_yoy` text COLLATE utf8mb4_bin COMMENT '中国:CPI:同比涨幅',
  `ppi_yoy` text COLLATE utf8mb4_bin COMMENT '中国:PPI:全部工业品:同比涨幅',
  `m2_yoy` text COLLATE utf8mb4_bin COMMENT '中国:M2:同比增速',
  `tsf_stock_yoy` text COLLATE utf8mb4_bin COMMENT '中国:社会融资规模存量:同比增速',
  `lpr_1y` text COLLATE utf8mb4_bin COMMENT '贷款市场报价利率(LPR):1年',
  `dr007` text COLLATE utf8mb4_bin COMMENT '银行间存款类金融机构7天质押式回购加权利率(DR007)',
  `pmi_manu` text COLLATE utf8mb4_bin COMMENT '中国:PMI',
  `pmi_serv` text COLLATE utf8mb4_bin COMMENT '中国:非制造业PMI:商务活动',
  `industry_yoy` text COLLATE utf8mb4_bin COMMENT '中国:工业增加值:同比增速',
  `fx_cny_mid` text COLLATE utf8mb4_bin COMMENT '中间价:美元兑人民币(时间序列数据)',
  `retail_sales_yoy` text COLLATE utf8mb4_bin COMMENT '中国:社会消费品零售总额:累计同比增速',
  `created_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建人',
  `created_time` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_by` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '修改人',
  `updated_time` datetime DEFAULT NULL COMMENT '修改时间',
  `gdp_real_yoy` text COLLATE utf8mb4_bin COMMENT '中国:GDP:不变价:当季同比增速',
  `urban_surveyed_unemployment_rate` text COLLATE utf8mb4_bin COMMENT '中国:城镇调查失业率(时间序列数据)',
  `brent_crude` text COLLATE utf8mb4_bin COMMENT '期货收盘价(连续):ICE布油',
  `xausd` text COLLATE utf8mb4_bin COMMENT '期货收盘价(连续):COMEX黄金(时间序列数据)',
  `m1_yoy` text COLLATE utf8mb4_bin COMMENT '中国:M1:同比增速',
  `aa_credit_yield_3y` text COLLATE utf8mb4_bin COMMENT 'AA级信用债收益率(3年)',
  `cgb_1y` text COLLATE utf8mb4_bin COMMENT '中债国债到期收益率:1年',
  `cgb_3y` text COLLATE utf8mb4_bin COMMENT '中债国债到期收益率:3年',
  `cgb_10y` text COLLATE utf8mb4_bin COMMENT '中债国债到期收益率:10年',
  `consumer_confidence` text COLLATE utf8mb4_bin COMMENT '中国:消费者信心指数(时间序列数据)',
  `infra_invest_cum_yoy` text COLLATE utf8mb4_bin COMMENT '中国:基础设施投资:累计同比增速',
  `manufacturing_invest_cum_yoy` text COLLATE utf8mb4_bin COMMENT '中国:制造业投资:累计同比增速',
  `real_estate_invest_cum_yoy` text COLLATE utf8mb4_bin COMMENT '中国:房地产开发投资完成额:累计同比增速',
  `resid_house_sales_cumulative_yoy` text COLLATE utf8mb4_bin COMMENT '商品房销售额:住宅:累计同比增速',
  `export_amount_yoy` text COLLATE utf8mb4_bin COMMENT '中国:出口金额:同比/累计同比增速',
  `import_amount_yoy` text COLLATE utf8mb4_bin COMMENT '中国:进口金额:同比/累计同比增速',
  `pmi_new_export_orders` text COLLATE utf8mb4_bin COMMENT '中国:PMI:新出口订单',
  `gov_expend_cumulative_yoy` text COLLATE utf8mb4_bin COMMENT '中国:财政预算支出:累计同比增速',
  `special_bond_issue_cum` text COLLATE utf8mb4_bin COMMENT '中国:新增专项债:累计值(时间序列数据)',
  `local_special_bond_target_annual` text COLLATE utf8mb4_bin COMMENT '中国:政府预期目标:地方专项债',
  `asset_volatility_sigma` text COLLATE utf8mb4_bin COMMENT '大类资产年化波动率(时间序列数据)',
  `asset_covariance_matrix_sigma` text COLLATE utf8mb4_bin COMMENT '大类资产年化协方差矩阵(时间序列数据)',
  `asset_correlation_matrix_rho` text COLLATE utf8mb4_bin COMMENT '大类资产长期相关性矩阵(时间序列数据)',
  `risk_free_rate_rf` text COLLATE utf8mb4_bin COMMENT '无风险利率期限结构(时间序列数据)',
  `asset_benchmark_profile` text COLLATE utf8mb4_bin COMMENT '四大类资产基准画像(时间序列数据)',
  `asset_expected_return_mu` text COLLATE utf8mb4_bin COMMENT '四大类资产预期收益向量(时间序列数据)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_aisa_macro_snapshot_monthly_3` (`snap_month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='aisa宏观指标月度快照（供LLM/报告直接消费）扁平化容器表';
